### ISSUE TITLE
some colors are off

### ISSUE THREAD

**Issue by zman32** [mkaflowski/Media-Style-Palette#2]
I've found that sometimes yours is different from androids all thou in the case of this album yours looks better 
![androidpalette](https://user-images.githubusercontent.com/620723/41328265-093957dc-6e7c-11e8-884a-cfd9be030cb3.jpg)
also can someone point me to code to fade the image to the color like that please?
thanks :)

**Comment by mkaflowski** [comment]
The difference of several pixels can make the difference so if they use some image loading library like Picasso or shrink image to optimize for notification it will probably be different.
Furthermore the implementation for for Adroid MediaStyle can be different in newer Androids. I used the implementation from Oreo.
Thank you for feedback :)
