### ISSUE TITLE
I wonder how this code works

### ISSUE THREAD

**Issue by jeho1335** [mkaflowski/Media-Style-Palette#4]
Hi.
I am making good use of your Media-Style-Palette library.
I would like to thank you for giving me a good library.

I wonder how this code works.
Could you tell me how this code works?

thank you.

**Comment by mkaflowski** [comment]
Hello. Thank you :) I have use code from Android Open Source Project.

**Comment by jeho1335** [comment]
Thank you for your reply.

I would like to ask you an additional question,

Currently, the internal code is being handled synchronously. Can I update it asynchronously?

Thank you.

**Comment by mkaflowski** [comment]
Yes, sure

wt., 5 mar 2019, 02:57 użytkownik OH JE HO <notifications@github.com>
napisał:

**Comment by mkaflowski** [comment]
Async methods added in recent version! :)

**Comment by jeho1335** [comment]
Extreamly thanks. :)
